# Generated by Django 4.2.5 on 2023-09-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='status',
            field=models.CharField(choices=[('Sent', 'Not Sent'), ('Sent', 'Not Sent')], default='Not Sent', max_length=15),
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
