# Generated by Django 4.2.5 on 2023-09-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_mails_status_delete_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_sent',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('Sent', 'Not Sent'), ('Sent', 'Not Sent')], default='Not Sent', max_length=20),
        ),
    ]
