# Generated by Django 4.2.5 on 2023-09-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_remove_message_is_sent_message_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mails',
            options={'ordering': ['pk']},
        ),
        migrations.AddIndex(
            model_name='mails',
            index=models.Index(fields=['client_phone_code', 'client_tag'], name='filter_indexes'),
        ),
    ]
