# Generated by Django 4.2.5 on 2023-09-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0005_alter_mails_options_mails_filter_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_code',
            field=models.SmallIntegerField(default=998),
        ),
    ]
